### PR TITLE
Enable SSL support

### PR DESCRIPTION
**Pull request by MaciejLukianski**
I added SSL support based on a new flag DRUPAL_SSL. This way apache can be automatically enabled for https://

### CODE REVIEW

**Comment by Boran** [comment]
Great! 
A few comments
- Prefix default-ssl with a number so the order of execution is clear, I believe this is a convention.
- Should really be copied to sites-available and then the link in sites-enabled created with a2ensite ? IN the the correct default site is not done cleanly either
- It would have been better to generate a new cert during first boot in start.sh, otherwise all instances on this image have exactly the same certificate. Such a certs could have some details such as the site name correctly in there. Is that difficult?

**Comment by MaciejLukianski** [comment]
Hi,
* default-ssl.conf - this is the name of the file that is created by default installer so I suppose we should stick to this? It is as generic as could be I just added stuff required by drupal (Allow override).
* I just followed your convention. You copy 000-default.conf directly do sites-enabled. Do you want to change both then? To me this does not matter too much when you really have just one site on a machine.
* Not sure what you mean here "*IN the the correct default site is not done cleanly either*"
* I now regenerate the snakeoil cert key during run. This way we stay very generic but also have different cert on each machine

**Comment by Boran** [comment]
* Ah, I had presume the apache default would be 001-default-ssl, but I see you are right, it is default-ssl.conf
* Yes I copied directly to sites-enabled, but in fact that is not nice (i.e. a bug), it would be good to do the ssl right, and also correct 000-default.conf so that both are added to sites-available and then enabled with a2ensite.
* typo above, sorry: "correct" > "current". We covered that in the previous line.
* use of make-ssl-cert: great!

Also, I needed to add $_SERVER['HTTPS'] = 'on'; to /var/www/html/sites/default/settings.php on a recent test site I had here (otherwise there were problems with mixed http/https content in Drupal).
Perhaps you could see if thats an issue for you too, and if so add that to the end of settings.php in start.sh after the site has been setup, when SSL has been enabled?

**Comment by Boran** [comment]
Maciej, can we get this finished up so I can commit? What is the status on your side, do you need help?

**Comment by MaciejLukianski** [comment]
Hi, sorry
Apache is done.
As to setting vars in settings.php I would be reluctant. There are other methods to achieve this as well which are widely used in drupal like securepages module for example which allows you to secure only chosen pages.

**Comment by Boran** [comment]
Tested on my side too, it is fine.
Committed. Good work, thanks!

**Comment by Boran** [comment]
Refreshed the boran/drupal docker image and pushed to docker hub too.

**Pull request merged**
